# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

# 마우스 키 활성화
CONFIG_ZMK_POINTING=y

# BLE 전송 파워 강화 (+8dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# macOS 연결 안정성 및 절전 해제 지연 방지
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
